// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsJsondb "github.com/kuetix/std-jsondb/modules/jsondb/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["jsondb"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"jsondb"+"/"+"collection", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "collection", Impl: transitionsJsondb.NewCollectionTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"jsondb"+"/"+"database", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "database", Impl: transitionsJsondb.NewDatabaseTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"jsondb"+"/"+"document", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "document", Impl: transitionsJsondb.NewDocumentTransitions() }})
		di.ToResolve(defines.TransitionPrefix+"jsondb"+"/"+"index", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "index", Impl: transitionsJsondb.NewIndexTransitions() }})
	}
}
